from enum import Enum


class StringEnum(str, Enum):
    """Python 3.9-compatible string enum base."""


class AnalysisRunStatus(StringEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class PipelineStage(StringEnum):
    NOT_STARTED = "NOT_STARTED"
    SCOPE_RESOLUTION = "SCOPE_RESOLUTION"
    DATA_ACQUISITION = "DATA_ACQUISITION"
    CLEANING_AND_NORMALIZATION = "CLEANING_AND_NORMALIZATION"
    SEMANTIC_TOPIC_DISCOVERY = "SEMANTIC_TOPIC_DISCOVERY"
    FINDING_EXTRACTION = "FINDING_EXTRACTION"
    TOPIC_CONSOLIDATION = "TOPIC_CONSOLIDATION"
    FINDING_CONSOLIDATION = "FINDING_CONSOLIDATION"
    EVIDENCE_EVALUATION = "EVIDENCE_EVALUATION"
    EVIDENCE_VALIDATION = "EVIDENCE_VALIDATION"
    CONFLICT_ANALYSIS = "CONFLICT_ANALYSIS"
    FINDING_FINALIZATION = "FINDING_FINALIZATION"
    REQUIREMENT_GENERATION = "REQUIREMENT_GENERATION"
    VERSION_PLANNING = "VERSION_PLANNING"
    PRD_GENERATION = "PRD_GENERATION"
    TEST_CASE_GENERATION = "TEST_CASE_GENERATION"
    TRACEABILITY_VALIDATION = "TRACEABILITY_VALIDATION"


class SourceType(StringEnum):
    APP_STORE = "app_store"
    CSV = "csv"
    JSON = "json"
    CACHED = "cached"
    DEMO = "demo"


class AnalysisOutputLanguage(StringEnum):
    FOLLOW_UI = "FOLLOW_UI"
    ZH_CN = "zh-CN"
    EN_US = "en-US"


class CandidateStatus(StringEnum):
    UNVALIDATED_CANDIDATE = "UNVALIDATED_CANDIDATE"


class AuditArtifactType(StringEnum):
    TOPIC_DRAFT = "TOPIC_DRAFT"
    FINDING_DRAFT = "FINDING_DRAFT"
    CONSOLIDATION_DRAFT = "CONSOLIDATION_DRAFT"
    EVIDENCE_VALIDATION = "EVIDENCE_VALIDATION"
    REQUIREMENT_DRAFT = "REQUIREMENT_DRAFT"
    REQUIREMENT_REVISION = "REQUIREMENT_REVISION"
    VERSION_PLAN_DRAFT = "VERSION_PLAN_DRAFT"
    STRUCTURED_PRD_DRAFT = "STRUCTURED_PRD_DRAFT"
    TEST_CASE_DRAFT = "TEST_CASE_DRAFT"
    VALIDATION_AUDIT = "VALIDATION_AUDIT"


class EvidenceStance(StringEnum):
    SUPPORTS = "SUPPORTS"
    CONFLICTS = "CONFLICTS"
    NEUTRAL = "NEUTRAL"
    IRRELEVANT = "IRRELEVANT"


class FindingEvidenceStatus(StringEnum):
    SUPPORTED = "SUPPORTED"
    WEAK = "WEAK"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT = "INSUFFICIENT"
    UNSUPPORTED = "UNSUPPORTED"


class EvidenceStrength(StringEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ArtifactValidationStatus(StringEnum):
    ACCEPTED = "ACCEPTED"
    REVISED = "REVISED"
    REJECTED = "REJECTED"
    ASSUMPTION = "ASSUMPTION"


class RequirementPriority(StringEnum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


class ImpactLevel(StringEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RequirementGroundingVerdict(StringEnum):
    GROUNDED = "GROUNDED"
    PARTIAL = "PARTIAL"
    UNGROUNDED = "UNGROUNDED"


class TestCaseType(StringEnum):
    FUNCTIONAL = "FUNCTIONAL"
    REGRESSION = "REGRESSION"
    NEGATIVE = "NEGATIVE"
    EDGE_CASE = "EDGE_CASE"
